### ISSUE TITLE
Checklist stable release

### ISSUE THREAD

**Issue by Legion2** [Legion2/CorsairLightingProtocol#101]
Before the first stable release 1.0.0 there are some things that has to be addressed.
- [ ] add the debug sketch to the github action ci
- [ ] use the namespace CLP for all classes and types
- [ ] move code from sketches (CommanderPRO...) to library `src`
- [ ] add some documentation about examples
- [ ] use a more generic FastLED led chip type for all examples
- [ ] add a CLP debug board for the debug sketch
- [ ] generate a new default serial number

**Comment by Legion2** [comment]
I have currently not much time to work on this. But I think the current implementation works very well and have no known bugs. So this refactoring can wait.
